# Generated by Django 4.1.4 on 2022-12-29 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webpages', '0002_slider_contact_create_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='slider',
            name='photo',
            field=models.ImageField(upload_to='static/media/slider/%Y/'),
        ),
    ]
